### ISSUE TITLE
The inference speed for English model got significantly slower after versioning up

### ISSUE THREAD

**Issue by gordon0414** [litagin02/Style-Bert-VITS2#104] opened 2024-03-22 06:14 UTC
Hello, thanks for the amazing project.
Recently I saw some major version update (to 2.4.1) and I tried it with my models which were trained on version 2.3.
It worked fine for JP-Extra models, and the inference speed for English model got about x5 slower..
0.3~0.4 seconds to over 1.8 seconds

I checked whether the models were loaded on GPU, and it was fine..

I might make a pull request if I solve the problem, but I think you should know in advance.

**Comment by litagin02** [comment] 2024-03-22 07:00
Sorry for convenience. I tested my old model (not JP-Extra model) and synthesize English speech, but inference speed is not so slow and seems no problem in my environment, so cannot reproduce it.

It may possible that in the first time of synthesis, English bert model is loaded and this takes extra time and this may be the cause, but once the bert model has been loaded, then inference should not be so slow.

**Comment by gordon0414** [comment] 2024-03-22 07:54
well I warmed up the model (of course loaded the BERT model too) and tested it on different machines.
there might be something that I'm missing.
will notify if I see some progressions.

**Comment by litagin02** [comment] 2024-06-02 07:09
Merged and updated officially in ver 2.5.0. Thanks for PR!

**Closed by litagin02** 2024-06-02 07:09 UTC
